// src/actions/types.js

// Language preferences
export const SET_LAN_PREFERENCE = "SET_LAN_PREFERENCE";

// Auth actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CHECK_TOKEN_REQUEST = "CHECK_TOKEN_REQUEST";
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS";
export const CHECK_TOKEN_FAILURE = "CHECK_TOKEN_FAILURE";

export const LOGOUT = "LOGOUT";

// Cuenta actions
export const GET_CUENTA_REQUEST = "GET_CUENTA_REQUEST";
export const GET_CUENTA_SUCCESS = "GET_CUENTA_SUCCESS";
export const GET_CUENTA_FAILURE = "GET_CUENTA_FAILURE";

export const UPDATE_CUENTA_REQUEST = "UPDATE_CUENTA_REQUEST";
export const UPDATE_CUENTA_SUCCESS = "UPDATE_CUENTA_SUCCESS";
export const UPDATE_CUENTA_FAILURE = "UPDATE_CUENTA_FAILURE";

// Usuarios actions
export const GET_USUARIOS_REQUEST = "GET_USUARIOS_REQUEST";
export const GET_USUARIOS_SUCCESS = "GET_USUARIOS_SUCCESS";
export const GET_USUARIOS_FAILURE = "GET_USUARIOS_FAILURE";

export const CREATE_USUARIO_REQUEST = "CREATE_USUARIO_REQUEST";
export const CREATE_USUARIO_SUCCESS = "CREATE_USUARIO_SUCCESS";
export const CREATE_USUARIO_FAILURE = "CREATE_USUARIO_FAILURE";

export const UPDATE_USUARIO_REQUEST = "UPDATE_USUARIO_REQUEST";
export const UPDATE_USUARIO_SUCCESS = "UPDATE_USUARIO_SUCCESS";
export const UPDATE_USUARIO_FAILURE = "UPDATE_USUARIO_FAILURE";

export const DELETE_USUARIO_REQUEST = "DELETE_USUARIO_REQUEST";
export const DELETE_USUARIO_SUCCESS = "DELETE_USUARIO_SUCCESS";
export const DELETE_USUARIO_FAILURE = "DELETE_USUARIO_FAILURE";
