// Language preferences
export const SET_LAN_PREFERENCE = "SET_LAN_PREFERENCE";

// Auth Types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CHECK_TOKEN_REQUEST = "CHECK_TOKEN_REQUEST";
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS";
export const CHECK_TOKEN_FAILURE = "CHECK_TOKEN_FAILURE";

export const LOGOUT = "LOGOUT";

// Permiso Types
export const PERMISO_CREATE_REQUEST = "PERMISO_CREATE_REQUEST";
export const PERMISO_CREATE_SUCCESS = "PERMISO_CREATE_SUCCESS";
export const PERMISO_CREATE_FAILURE = "PERMISO_CREATE_FAILURE";

export const PERMISO_FIND_ALL_REQUEST = "PERMISO_FIND_ALL_REQUEST";
export const PERMISO_FIND_ALL_SUCCESS = "PERMISO_FIND_ALL_SUCCESS";
export const PERMISO_FIND_ALL_FAILURE = "PERMISO_FIND_ALL_FAILURE";

export const PERMISO_FIND_ONE_REQUEST = "PERMISO_FIND_ONE_REQUEST";
export const PERMISO_FIND_ONE_SUCCESS = "PERMISO_FIND_ONE_SUCCESS";
export const PERMISO_FIND_ONE_FAILURE = "PERMISO_FIND_ONE_FAILURE";

export const PERMISO_UPDATE_REQUEST = "PERMISO_UPDATE_REQUEST";
export const PERMISO_UPDATE_SUCCESS = "PERMISO_UPDATE_SUCCESS";
export const PERMISO_UPDATE_FAILURE = "PERMISO_UPDATE_FAILURE";

export const PERMISO_REMOVE_REQUEST = "PERMISO_REMOVE_REQUEST";
export const PERMISO_REMOVE_SUCCESS = "PERMISO_REMOVE_SUCCESS";
export const PERMISO_REMOVE_FAILURE = "PERMISO_REMOVE_FAILURE";

// Rol Types
export const ROL_CREATE_REQUEST = "ROL_CREATE_REQUEST";
export const ROL_CREATE_SUCCESS = "ROL_CREATE_SUCCESS";
export const ROL_CREATE_FAILURE = "ROL_CREATE_FAILURE";

export const ROL_FIND_ALL_REQUEST = "ROL_FIND_ALL_REQUEST";
export const ROL_FIND_ALL_SUCCESS = "ROL_FIND_ALL_SUCCESS";
export const ROL_FIND_ALL_FAILURE = "ROL_FIND_ALL_FAILURE";

export const ROL_FIND_ONE_REQUEST = "ROL_FIND_ONE_REQUEST";
export const ROL_FIND_ONE_SUCCESS = "ROL_FIND_ONE_SUCCESS";
export const ROL_FIND_ONE_FAILURE = "ROL_FIND_ONE_FAILURE";

export const ROL_UPDATE_REQUEST = "ROL_UPDATE_REQUEST";
export const ROL_UPDATE_SUCCESS = "ROL_UPDATE_SUCCESS";
export const ROL_UPDATE_FAILURE = "ROL_UPDATE_FAILURE";

export const ROL_REMOVE_REQUEST = "ROL_REMOVE_REQUEST";
export const ROL_REMOVE_SUCCESS = "ROL_REMOVE_SUCCESS";
export const ROL_REMOVE_FAILURE = "ROL_REMOVE_FAILURE";

// Cuenta Types
export const CUENTA_CREATE_REQUEST = "CUENTA_CREATE_REQUEST";
export const CUENTA_CREATE_SUCCESS = "CUENTA_CREATE_SUCCESS";
export const CUENTA_CREATE_FAILURE = "CUENTA_CREATE_FAILURE";

export const CUENTA_FIND_ALL_REQUEST = "CUENTA_FIND_ALL_REQUEST";
export const CUENTA_FIND_ALL_SUCCESS = "CUENTA_FIND_ALL_SUCCESS";
export const CUENTA_FIND_ALL_FAILURE = "CUENTA_FIND_ALL_FAILURE";

export const CUENTA_FIND_ONE_REQUEST = "CUENTA_FIND_ONE_REQUEST";
export const CUENTA_FIND_ONE_SUCCESS = "CUENTA_FIND_ONE_SUCCESS";
export const CUENTA_FIND_ONE_FAILURE = "CUENTA_FIND_ONE_FAILURE";

export const CUENTA_DELETE_REQUEST = "CUENTA_DELETE_REQUEST";
export const CUENTA_DELETE_SUCCESS = "CUENTA_DELETE_SUCCESS";
export const CUENTA_DELETE_FAILURE = "CUENTA_DELETE_FAILURE";

export const CUENTA_CAMBIAR_ESTADO_REQUEST = "CUENTA_CAMBIAR_ESTADO_REQUEST";
export const CUENTA_CAMBIAR_ESTADO_SUCCESS = "CUENTA_CAMBIAR_ESTADO_SUCCESS";
export const CUENTA_CAMBIAR_ESTADO_FAILURE = "CUENTA_CAMBIAR_ESTADO_FAILURE";

// Usuario Types
export const USUARIO_CREATE_REQUEST = "USUARIO_CREATE_REQUEST";
export const USUARIO_CREATE_SUCCESS = "USUARIO_CREATE_SUCCESS";
export const USUARIO_CREATE_FAILURE = "USUARIO_CREATE_FAILURE";

export const USUARIO_FIND_ALL_REQUEST = "USUARIO_FIND_ALL_REQUEST";
export const USUARIO_FIND_ALL_SUCCESS = "USUARIO_FIND_ALL_SUCCESS";
export const USUARIO_FIND_ALL_FAILURE = "USUARIO_FIND_ALL_FAILURE";

export const USUARIO_FIND_ONE_REQUEST = "USUARIO_FIND_ONE_REQUEST";
export const USUARIO_FIND_ONE_SUCCESS = "USUARIO_FIND_ONE_SUCCESS";
export const USUARIO_FIND_ONE_FAILURE = "USUARIO_FIND_ONE_FAILURE";

export const USUARIO_UPDATE_REQUEST = "USUARIO_UPDATE_REQUEST";
export const USUARIO_UPDATE_SUCCESS = "USUARIO_UPDATE_SUCCESS";
export const USUARIO_UPDATE_FAILURE = "USUARIO_UPDATE_FAILURE";

export const USUARIO_UPDATE_ROL_REQUEST = "USUARIO_UPDATE_ROL_REQUEST";
export const USUARIO_UPDATE_ROL_SUCCESS = "USUARIO_UPDATE_ROL_SUCCESS";
export const USUARIO_UPDATE_ROL_FAILURE = "USUARIO_UPDATE_ROL_FAILURE";

// Registrar Types
export const REGISTRAR_CREATE_REQUEST = "REGISTRAR_CREATE_REQUEST";
export const REGISTRAR_CREATE_SUCCESS = "REGISTRAR_CREATE_SUCCESS";
export const REGISTRAR_CREATE_FAILURE = "REGISTRAR_CREATE_FAILURE";

// Organizacion Types
export const ORGANIZACION_CREATE_REQUEST = "ORGANIZACION_CREATE_REQUEST";
export const ORGANIZACION_CREATE_SUCCESS = "ORGANIZACION_CREATE_SUCCESS";
export const ORGANIZACION_CREATE_FAILURE = "ORGANIZACION_CREATE_FAILURE";

export const ORGANIZACION_FIND_ALL_REQUEST = "ORGANIZACION_FIND_ALL_REQUEST";
export const ORGANIZACION_FIND_ALL_SUCCESS = "ORGANIZACION_FIND_ALL_SUCCESS";
export const ORGANIZACION_FIND_ALL_FAILURE = "ORGANIZACION_FIND_ALL_FAILURE";

export const ORGANIZACION_FIND_ONE_REQUEST = "ORGANIZACION_FIND_ONE_REQUEST";
export const ORGANIZACION_FIND_ONE_SUCCESS = "ORGANIZACION_FIND_ONE_SUCCESS";
export const ORGANIZACION_FIND_ONE_FAILURE = "ORGANIZACION_FIND_ONE_FAILURE";

export const ORGANIZACION_UPDATE_REQUEST = "ORGANIZACION_UPDATE_REQUEST";
export const ORGANIZACION_UPDATE_SUCCESS = "ORGANIZACION_UPDATE_SUCCESS";
export const ORGANIZACION_UPDATE_FAILURE = "ORGANIZACION_UPDATE_FAILURE";

// Proyecto Types
export const PROYECTO_CREATE_REQUEST = "PROYECTO_CREATE_REQUEST";
export const PROYECTO_CREATE_SUCCESS = "PROYECTO_CREATE_SUCCESS";
export const PROYECTO_CREATE_FAILURE = "PROYECTO_CREATE_FAILURE";

export const PROYECTO_FIND_ALL_REQUEST = "PROYECTO_FIND_ALL_REQUEST";
export const PROYECTO_FIND_ALL_SUCCESS = "PROYECTO_FIND_ALL_SUCCESS";
export const PROYECTO_FIND_ALL_FAILURE = "PROYECTO_FIND_ALL_FAILURE";

export const PROYECTO_FIND_ONE_REQUEST = "PROYECTO_FIND_ONE_REQUEST";
export const PROYECTO_FIND_ONE_SUCCESS = "PROYECTO_FIND_ONE_SUCCESS";
export const PROYECTO_FIND_ONE_FAILURE = "PROYECTO_FIND_ONE_FAILURE";

export const PROYECTO_UPDATE_REQUEST = "PROYECTO_UPDATE_REQUEST";
export const PROYECTO_UPDATE_SUCCESS = "PROYECTO_UPDATE_SUCCESS";
export const PROYECTO_UPDATE_FAILURE = "PROYECTO_UPDATE_FAILURE";

export const PROYECTO_REMOVE_REQUEST = "PROYECTO_REMOVE_REQUEST";
export const PROYECTO_REMOVE_SUCCESS = "PROYECTO_REMOVE_SUCCESS";
export const PROYECTO_REMOVE_FAILURE = "PROYECTO_REMOVE_FAILURE";

export const PROYECTO_FIND_BY_CUENTA_REQUEST =
  "PROYECTO_FIND_BY_CUENTA_REQUEST";
export const PROYECTO_FIND_BY_CUENTA_SUCCESS =
  "PROYECTO_FIND_BY_CUENTA_SUCCESS";
export const PROYECTO_FIND_BY_CUENTA_FAILURE =
  "PROYECTO_FIND_BY_CUENTA_FAILURE";

// Maquina Types
export const MAQUINA_CREATE_REQUEST = "MAQUINA_CREATE_REQUEST";
export const MAQUINA_CREATE_SUCCESS = "MAQUINA_CREATE_SUCCESS";
export const MAQUINA_CREATE_FAILURE = "MAQUINA_CREATE_FAILURE";

export const MAQUINA_FIND_ALL_REQUEST = "MAQUINA_FIND_ALL_REQUEST";
export const MAQUINA_FIND_ALL_SUCCESS = "MAQUINA_FIND_ALL_SUCCESS";
export const MAQUINA_FIND_ALL_FAILURE = "MAQUINA_FIND_ALL_FAILURE";

export const MAQUINA_FIND_ONE_REQUEST = "MAQUINA_FIND_ONE_REQUEST";
export const MAQUINA_FIND_ONE_SUCCESS = "MAQUINA_FIND_ONE_SUCCESS";
export const MAQUINA_FIND_ONE_FAILURE = "MAQUINA_FIND_ONE_FAILURE";

export const MAQUINA_UPDATE_REQUEST = "MAQUINA_UPDATE_REQUEST";
export const MAQUINA_UPDATE_SUCCESS = "MAQUINA_UPDATE_SUCCESS";
export const MAQUINA_UPDATE_FAILURE = "MAQUINA_UPDATE_FAILURE";

export const MAQUINA_REMOVE_REQUEST = "MAQUINA_REMOVE_REQUEST";
export const MAQUINA_REMOVE_SUCCESS = "MAQUINA_REMOVE_SUCCESS";
export const MAQUINA_REMOVE_FAILURE = "MAQUINA_REMOVE_FAILURE";

export const MAQUINA_FIND_BY_PROYECTO_REQUEST =
  "MAQUINA_FIND_BY_PROYECTO_REQUEST";
export const MAQUINA_FIND_BY_PROYECTO_SUCCESS =
  "MAQUINA_FIND_BY_PROYECTO_SUCCESS";
export const MAQUINA_FIND_BY_PROYECTO_FAILURE =
  "MAQUINA_FIND_BY_PROYECTO_FAILURE";

// Contribuyente Types
export const CONTRIBUYENTE_CREATE_REQUEST = "CONTRIBUYENTE_CREATE_REQUEST";
export const CONTRIBUYENTE_CREATE_SUCCESS = "CONTRIBUYENTE_CREATE_SUCCESS";
export const CONTRIBUYENTE_CREATE_FAILURE = "CONTRIBUYENTE_CREATE_FAILURE";

export const CONTRIBUYENTE_FIND_ALL_REQUEST = "CONTRIBUYENTE_FIND_ALL_REQUEST";
export const CONTRIBUYENTE_FIND_ALL_SUCCESS = "CONTRIBUYENTE_FIND_ALL_SUCCESS";
export const CONTRIBUYENTE_FIND_ALL_FAILURE = "CONTRIBUYENTE_FIND_ALL_FAILURE";

export const CONTRIBUYENTE_FIND_ONE_REQUEST = "CONTRIBUYENTE_FIND_ONE_REQUEST";
export const CONTRIBUYENTE_FIND_ONE_SUCCESS = "CONTRIBUYENTE_FIND_ONE_SUCCESS";
export const CONTRIBUYENTE_FIND_ONE_FAILURE = "CONTRIBUYENTE_FIND_ONE_FAILURE";

export const CONTRIBUYENTE_UPDATE_REQUEST = "CONTRIBUYENTE_UPDATE_REQUEST";
export const CONTRIBUYENTE_UPDATE_SUCCESS = "CONTRIBUYENTE_UPDATE_SUCCESS";
export const CONTRIBUYENTE_UPDATE_FAILURE = "CONTRIBUYENTE_UPDATE_FAILURE";

export const CONTRIBUYENTE_REMOVE_REQUEST = "CONTRIBUYENTE_REMOVE_REQUEST";
export const CONTRIBUYENTE_REMOVE_SUCCESS = "CONTRIBUYENTE_REMOVE_SUCCESS";
export const CONTRIBUYENTE_REMOVE_FAILURE = "CONTRIBUYENTE_REMOVE_FAILURE";

// Hito Types
export const HITO_CREATE_REQUEST = "HITO_CREATE_REQUEST";
export const HITO_CREATE_SUCCESS = "HITO_CREATE_SUCCESS";
export const HITO_CREATE_FAILURE = "HITO_CREATE_FAILURE";

export const HITO_FIND_ALL_REQUEST = "HITO_FIND_ALL_REQUEST";
export const HITO_FIND_ALL_SUCCESS = "HITO_FIND_ALL_SUCCESS";
export const HITO_FIND_ALL_FAILURE = "HITO_FIND_ALL_FAILURE";

export const HITO_FIND_ONE_REQUEST = "HITO_FIND_ONE_REQUEST";
export const HITO_FIND_ONE_SUCCESS = "HITO_FIND_ONE_SUCCESS";
export const HITO_FIND_ONE_FAILURE = "HITO_FIND_ONE_FAILURE";

export const HITO_UPDATE_REQUEST = "HITO_UPDATE_REQUEST";
export const HITO_UPDATE_SUCCESS = "HITO_UPDATE_SUCCESS";
export const HITO_UPDATE_FAILURE = "HITO_UPDATE_FAILURE";

export const HITO_REMOVE_REQUEST = "HITO_REMOVE_REQUEST";
export const HITO_REMOVE_SUCCESS = "HITO_REMOVE_SUCCESS";
export const HITO_REMOVE_FAILURE = "HITO_REMOVE_FAILURE";

// ContextoDeAplicacion Types
export const CONTEXTO_DE_APLICACION_CREATE_REQUEST =
  "CONTEXTO_DE_APLICACION_CREATE_REQUEST";
export const CONTEXTO_DE_APLICACION_CREATE_SUCCESS =
  "CONTEXTO_DE_APLICACION_CREATE_SUCCESS";
export const CONTEXTO_DE_APLICACION_CREATE_FAILURE =
  "CONTEXTO_DE_APLICACION_CREATE_FAILURE";

export const CONTEXTO_DE_APLICACION_FIND_ALL_REQUEST =
  "CONTEXTO_DE_APLICACION_FIND_ALL_REQUEST";
export const CONTEXTO_DE_APLICACION_FIND_ALL_SUCCESS =
  "CONTEXTO_DE_APLICACION_FIND_ALL_SUCCESS";
export const CONTEXTO_DE_APLICACION_FIND_ALL_FAILURE =
  "CONTEXTO_DE_APLICACION_FIND_ALL_FAILURE";

export const CONTEXTO_DE_APLICACION_FIND_ONE_REQUEST =
  "CONTEXTO_DE_APLICACION_FIND_ONE_REQUEST";
export const CONTEXTO_DE_APLICACION_FIND_ONE_SUCCESS =
  "CONTEXTO_DE_APLICACION_FIND_ONE_SUCCESS";
export const CONTEXTO_DE_APLICACION_FIND_ONE_FAILURE =
  "CONTEXTO_DE_APLICACION_FIND_ONE_FAILURE";

export const CONTEXTO_DE_APLICACION_UPDATE_REQUEST =
  "CONTEXTO_DE_APLICACION_UPDATE_REQUEST";
export const CONTEXTO_DE_APLICACION_UPDATE_SUCCESS =
  "CONTEXTO_DE_APLICACION_UPDATE_SUCCESS";
export const CONTEXTO_DE_APLICACION_UPDATE_FAILURE =
  "CONTEXTO_DE_APLICACION_UPDATE_FAILURE";

export const CONTEXTO_DE_APLICACION_REMOVE_REQUEST =
  "CONTEXTO_DE_APLICACION_REMOVE_REQUEST";
export const CONTEXTO_DE_APLICACION_REMOVE_SUCCESS =
  "CONTEXTO_DE_APLICACION_REMOVE_SUCCESS";
export const CONTEXTO_DE_APLICACION_REMOVE_FAILURE =
  "CONTEXTO_DE_APLICACION_REMOVE_FAILURE";

// CasoDeUso Types
export const CASO_DE_USO_CREATE_REQUEST = "CASO_DE_USO_CREATE_REQUEST";
export const CASO_DE_USO_CREATE_SUCCESS = "CASO_DE_USO_CREATE_SUCCESS";
export const CASO_DE_USO_CREATE_FAILURE = "CASO_DE_USO_CREATE_FAILURE";

export const CASO_DE_USO_FIND_ALL_REQUEST = "CASO_DE_USO_FIND_ALL_REQUEST";
export const CASO_DE_USO_FIND_ALL_SUCCESS = "CASO_DE_USO_FIND_ALL_SUCCESS";
export const CASO_DE_USO_FIND_ALL_FAILURE = "CASO_DE_USO_FIND_ALL_FAILURE";

export const CASO_DE_USO_FIND_ONE_REQUEST = "CASO_DE_USO_FIND_ONE_REQUEST";
export const CASO_DE_USO_FIND_ONE_SUCCESS = "CASO_DE_USO_FIND_ONE_SUCCESS";
export const CASO_DE_USO_FIND_ONE_FAILURE = "CASO_DE_USO_FIND_ONE_FAILURE";

export const CASO_DE_USO_UPDATE_REQUEST = "CASO_DE_USO_UPDATE_REQUEST";
export const CASO_DE_USO_UPDATE_SUCCESS = "CASO_DE_USO_UPDATE_SUCCESS";
export const CASO_DE_USO_UPDATE_FAILURE = "CASO_DE_USO_UPDATE_FAILURE";

export const CASO_DE_USO_REMOVE_REQUEST = "CASO_DE_USO_REMOVE_REQUEST";
export const CASO_DE_USO_REMOVE_SUCCESS = "CASO_DE_USO_REMOVE_SUCCESS";
export const CASO_DE_USO_REMOVE_FAILURE = "CASO_DE_USO_REMOVE_FAILURE";

// Tecnologia Types
export const TECNOLOGIA_CREATE_REQUEST = "TECNOLOGIA_CREATE_REQUEST";
export const TECNOLOGIA_CREATE_SUCCESS = "TECNOLOGIA_CREATE_SUCCESS";
export const TECNOLOGIA_CREATE_FAILURE = "TECNOLOGIA_CREATE_FAILURE";

export const TECNOLOGIA_FIND_ALL_REQUEST = "TECNOLOGIA_FIND_ALL_REQUEST";
export const TECNOLOGIA_FIND_ALL_SUCCESS = "TECNOLOGIA_FIND_ALL_SUCCESS";
export const TECNOLOGIA_FIND_ALL_FAILURE = "TECNOLOGIA_FIND_ALL_FAILURE";

export const TECNOLOGIA_FIND_ONE_REQUEST = "TECNOLOGIA_FIND_ONE_REQUEST";
export const TECNOLOGIA_FIND_ONE_SUCCESS = "TECNOLOGIA_FIND_ONE_SUCCESS";
export const TECNOLOGIA_FIND_ONE_FAILURE = "TECNOLOGIA_FIND_ONE_FAILURE";

export const TECNOLOGIA_UPDATE_REQUEST = "TECNOLOGIA_UPDATE_REQUEST";
export const TECNOLOGIA_UPDATE_SUCCESS = "TECNOLOGIA_UPDATE_SUCCESS";
export const TECNOLOGIA_UPDATE_FAILURE = "TECNOLOGIA_UPDATE_FAILURE";

export const TECNOLOGIA_REMOVE_REQUEST = "TECNOLOGIA_REMOVE_REQUEST";
export const TECNOLOGIA_REMOVE_SUCCESS = "TECNOLOGIA_REMOVE_SUCCESS";
export const TECNOLOGIA_REMOVE_FAILURE = "TECNOLOGIA_REMOVE_FAILURE";

// Like Types
export const LIKE_CREATE_REQUEST = "LIKE_CREATE_REQUEST";
export const LIKE_CREATE_SUCCESS = "LIKE_CREATE_SUCCESS";
export const LIKE_CREATE_FAILURE = "LIKE_CREATE_FAILURE";

export const LIKE_FIND_ALL_REQUEST = "LIKE_FIND_ALL_REQUEST";
export const LIKE_FIND_ALL_SUCCESS = "LIKE_FIND_ALL_SUCCESS";
export const LIKE_FIND_ALL_FAILURE = "LIKE_FIND_ALL_FAILURE";

export const LIKE_FIND_ONE_REQUEST = "LIKE_FIND_ONE_REQUEST";
export const LIKE_FIND_ONE_SUCCESS = "LIKE_FIND_ONE_SUCCESS";
export const LIKE_FIND_ONE_FAILURE = "LIKE_FIND_ONE_FAILURE";

export const LIKE_REMOVE_REQUEST = "LIKE_REMOVE_REQUEST";
export const LIKE_REMOVE_SUCCESS = "LIKE_REMOVE_SUCCESS";
export const LIKE_REMOVE_FAILURE = "LIKE_REMOVE_FAILURE";

// Curso Types
export const CURSO_CREATE_REQUEST = "CURSO_CREATE_REQUEST";
export const CURSO_CREATE_SUCCESS = "CURSO_CREATE_SUCCESS";
export const CURSO_CREATE_FAILURE = "CURSO_CREATE_FAILURE";

export const CURSO_FIND_ALL_REQUEST = "CURSO_FIND_ALL_REQUEST";
export const CURSO_FIND_ALL_SUCCESS = "CURSO_FIND_ALL_SUCCESS";
export const CURSO_FIND_ALL_FAILURE = "CURSO_FIND_ALL_FAILURE";

export const CURSO_FIND_ONE_REQUEST = "CURSO_FIND_ONE_REQUEST";
export const CURSO_FIND_ONE_SUCCESS = "CURSO_FIND_ONE_SUCCESS";
export const CURSO_FIND_ONE_FAILURE = "CURSO_FIND_ONE_FAILURE";

export const CURSO_UPDATE_REQUEST = "CURSO_UPDATE_REQUEST";
export const CURSO_UPDATE_SUCCESS = "CURSO_UPDATE_SUCCESS";
export const CURSO_UPDATE_FAILURE = "CURSO_UPDATE_FAILURE";

export const CURSO_REMOVE_REQUEST = "CURSO_REMOVE_REQUEST";
export const CURSO_REMOVE_SUCCESS = "CURSO_REMOVE_SUCCESS";
export const CURSO_REMOVE_FAILURE = "CURSO_REMOVE_FAILURE";

// Clase Types
export const CLASE_CREATE_REQUEST = "CLASE_CREATE_REQUEST";
export const CLASE_CREATE_SUCCESS = "CLASE_CREATE_SUCCESS";
export const CLASE_CREATE_FAILURE = "CLASE_CREATE_FAILURE";

export const CLASE_FIND_ALL_REQUEST = "CLASE_FIND_ALL_REQUEST";
export const CLASE_FIND_ALL_SUCCESS = "CLASE_FIND_ALL_SUCCESS";
export const CLASE_FIND_ALL_FAILURE = "CLASE_FIND_ALL_FAILURE";

export const CLASE_FIND_ONE_REQUEST = "CLASE_FIND_ONE_REQUEST";
export const CLASE_FIND_ONE_SUCCESS = "CLASE_FIND_ONE_SUCCESS";
export const CLASE_FIND_ONE_FAILURE = "CLASE_FIND_ONE_FAILURE";

export const CLASE_UPDATE_REQUEST = "CLASE_UPDATE_REQUEST";
export const CLASE_UPDATE_SUCCESS = "CLASE_UPDATE_SUCCESS";
export const CLASE_UPDATE_FAILURE = "CLASE_UPDATE_FAILURE";

export const CLASE_REMOVE_REQUEST = "CLASE_REMOVE_REQUEST";
export const CLASE_REMOVE_SUCCESS = "CLASE_REMOVE_SUCCESS";
export const CLASE_REMOVE_FAILURE = "CLASE_REMOVE_FAILURE";

// Comentario Types
export const COMENTARIO_CREATE_REQUEST = "COMENTARIO_CREATE_REQUEST";
export const COMENTARIO_CREATE_SUCCESS = "COMENTARIO_CREATE_SUCCESS";
export const COMENTARIO_CREATE_FAILURE = "COMENTARIO_CREATE_FAILURE";

export const COMENTARIO_FIND_ALL_REQUEST = "COMENTARIO_FIND_ALL_REQUEST";
export const COMENTARIO_FIND_ALL_SUCCESS = "COMENTARIO_FIND_ALL_SUCCESS";
export const COMENTARIO_FIND_ALL_FAILURE = "COMENTARIO_FIND_ALL_FAILURE";

export const COMENTARIO_FIND_ONE_REQUEST = "COMENTARIO_FIND_ONE_REQUEST";
export const COMENTARIO_FIND_ONE_SUCCESS = "COMENTARIO_FIND_ONE_SUCCESS";
export const COMENTARIO_FIND_ONE_FAILURE = "COMENTARIO_FIND_ONE_FAILURE";

export const COMENTARIO_UPDATE_REQUEST = "COMENTARIO_UPDATE_REQUEST";
export const COMENTARIO_UPDATE_SUCCESS = "COMENTARIO_UPDATE_SUCCESS";
export const COMENTARIO_UPDATE_FAILURE = "COMENTARIO_UPDATE_FAILURE";

export const COMENTARIO_REMOVE_REQUEST = "COMENTARIO_REMOVE_REQUEST";
export const COMENTARIO_REMOVE_SUCCESS = "COMENTARIO_REMOVE_SUCCESS";
export const COMENTARIO_REMOVE_FAILURE = "COMENTARIO_REMOVE_FAILURE";
